repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-yaml
    -   id: debug-statements
        exclude: tests/
    -   id: end-of-file-fixer
        exclude: tests/test_changes/
        files: \.(py|sh|yml|yaml)$
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        files: \.(py|sh|yml|yaml)$
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        exclude: tests/
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-blind-except',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-implicit-str-concat',
            'pydocstyle>=5.0.0',
        ]
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==23.1.0]
        exclude: ^.github/
