[tool.poetry]
name = "baraeja"
version = "0.1.0"
description = ""
authors = ["Astemir Boziev <bootuz07@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
