databases:
  - name: baraeja
    databaseName: baraeja
    user: baraeja

services:
  - type: web
    name: baraeja
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn baraeja.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: baraeja
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4