# Generated by Django 4.1.3 on 2022-11-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="book",
            name="category",
        ),
        migrations.RemoveField(
            model_name="book",
            name="publisher",
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="app.author", verbose_name="Author"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="categories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="app.category",
                verbose_name="Genre",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="publishers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="app.publisher",
                verbose_name="Publisher",
            ),
        ),
        migrations.AlterModelTable(
            name="author",
            table="author",
        ),
        migrations.AlterModelTable(
            name="book",
            table="book",
        ),
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
        migrations.AlterModelTable(
            name="publisher",
            table="publisher",
        ),
    ]
