# Generated by Django 4.1.3 on 2022-11-26 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_book_author_remove_book_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
