# Generated by Django 4.1.7 on 2023-04-02 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_category_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(max_length=100, verbose_name="Icon name"),
                ),
                (
                    "url",
                    models.URLField(max_length=100, unique=True, verbose_name="URL"),
                ),
            ],
        ),
    ]
