# Generated by Django 4.2 on 2023-04-09 10:49

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_socialmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app.models.user_directory_path,
                verbose_name="Cover",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="epub",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app.models.user_directory_path,
                verbose_name="EPUB",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app.models.user_directory_path,
                verbose_name="PDF",
            ),
        ),
    ]
