# Generated by Django 4.2 on 2023-04-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_book_cover_alter_book_epub_alter_book_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="books",
                to="app.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="ISBN"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="books",
                to="app.publisher",
                verbose_name="Publisher",
            ),
        ),
    ]
