# Generated by Django 4.2 on 2023-04-11 18:27

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_book_category_alter_book_isbn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app.models.author_directory,
                verbose_name="Photo",
            ),
        ),
    ]
