# Generated by Django 4.2 on 2023-04-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_book_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="ISBN"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("KӀАХЭ", "Адыгабзэ"), ("ЩХЬАГЪ", "Адыгэбзэ")],
                default="",
                max_length=20,
                verbose_name="Language",
            ),
        ),
    ]
