name: Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linter:
    uses: ./.github/workflows/base.yml
    steps:
      - name: Run linter
        run: |
          flake8